-- CONSTRAINT: MAKE SURE THAT MARKS ARE IN A LOGICAL RANGE
ALTER TABLE RESULT
ADD CONSTRAINT chk_marks CHECK (marks_obtained BETWEEN 0 AND 100);
-- PREVENT NEGATIVE FEE AMOUNTS
ALTER TABLE FEE PAYMENT
ADD CONSTRAINT chk_fee_positive CHECK (amount>=0);


